### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 27

### ISSUE THREAD

**Issue by jonathanslenders** [invisibleroads/socketIO-client#122]
Related to this issue: https://github.com/invisibleroads/socketIO-client/issues/81

I get an error at symmetries.py: 29 in decode_string.

I can't easily copy/paste the stack, but it looks like this:

![image](https://cloud.githubusercontent.com/assets/216638/18742705/fac06d36-80b5-11e6-9d62-8e47f400675b.png)

I guess, that adding an `errors="ignore"` option to the decode should work.
##

**Comment by invisibleroads** [comment]
Hmm, I don't think ignoring the UnicodeDecodeError is a good idea, since the packet_data will be empty and make future debugging hard.

Could it be that the string is using an encoding that is not utf-8?

@RobbieClarken says that #135 fixes this issue. Perhaps what happened is that six.b encoded the string using latin-1, but then decode_string tries to decode the string using utf-8, which will fail.

    '¥'.decode('utf-8').encode('latin-1').decode('utf-8')

Assuming this is what happened, I'm going to close this issue for now. Please reopen if it does not fix it.
