### ISSUE TITLE
Socket.IO v 1.0 is out [$100]

### ISSUE THREAD

**Issue by parrotmac** [invisibleroads/socketIO-client#52]
The latest stable Socket.IO is v1.0. This version changes the API, breaking this client.

**Comment by sarietta** [comment]
Any movement on this? I would like to try to get it ready for pip soon-ish.

**Comment by invisibleroads** [comment]
Hi Sean, if you can include the two scripts for starting and stopping the
test server, then I'll most likely merge your changes.

I disagree with having the heartbeat be a thread instead of a coroutine, as
multiprocessing.Process doubles the current process's memory use once it is
called. Some users wanted a tiny memory footprint.

For that reason, I'll make some changes before deploying to pypi.

Thanks for finding and solving issues related to server disruptions.

I should go through all the issues and pull requests too. I'll spend some
time on the 0.6.0 branch tomorrow. My concentration is shot to hell for
some reason. I keep forgetting what I'm doing.

**Comment by sarietta** [comment]
I don't think the memory footprint issue is at play here. This issue arises on OS's where shared memory needs to be copied across threads. In my implementation there is no shared memory. It's just a separate thread. You can think of it as simply another process that is running separately. It shouldn't retain any context from the spawning thread.

I realize memory footprint can be an issue (as you mentioned RPi in the pull request), but I have checked the memory overhead and it's negligible. In fact, I rewrote this library for the explicit reason that I needed it to run on a Raspberry Pi and have not had any issues :).

If it is still a concern, please provide some evidence that memory is indeed being over-used and I will implement a workaround. 

The heartbeat really ought to be in a separate thread or the entire library should be rewritten to be event-driven. Otherwise there is no way to guarantee that the heartbeat is called at the correct interval.

**Comment by invisibleroads** [comment]
You make a convincing argument that the [StackOverflow comment](http://stackoverflow.com/questions/14749897/python-multiprocessing-memory-usage) is referring to threads with shared memory.

It's possible that the newer multiprocessing module is cleaner than the original threading module.  [Simon Morley reported excessive memory use](https://github.com/invisibleroads/socketIO-client/issues/22)  for an [earlier version that used threading.Thread](https://github.com/invisibleroads/socketIO-client/blob/01f1d0d06c08cdb275d7c42382d4d7631c6616a8/socketIO_client/__init__.py).

The `start-test-server.sh` and `kill-test-server.sh` are missing from your commit.  I can replace them if you can't find the originals.

**Comment by sarietta** [comment]
I added them to the pull request: 

https://github.com/sarietta/socketIO-client/commit/2a43420e1b503100ea51cbe44d4db6f3b447183c

**Comment by invisibleroads** [comment]
Hmm, as much as I would like to approve this pull request, none of the tests are passing in Python 2.7.5 and enum 0.4.4.  The following portion fails.

    if packet.type is not parser.PacketType.OPEN:
        _log.warn("Got unexpected packet during connection handshake: %d" % packet.type);
        return None;

`packet.type` is an integer zero.

`parser.PacketType.OPEN` is an enum that contains a value attribute equal to the integer zero, but OPEN itself does not equal zero.

**Comment by invisibleroads** [comment]
I'll try to manually merge this pull request after making some modifications.

**Comment by sarietta** [comment]
Hmm. That's very odd. My tests seem to be fine on Python 2.7.6 and enum 0.4.4. 

I'm happy to implement a fix for this, or you can. It strikes me as odd that a minor version difference in Python would cause this bug. If there is something else amiss, please let me know and I will make sure to take care of it.

:)

**Comment by softforge** [comment]
I just wanted to check the status of this. What is blocking the SocketIO v1.x comparability from being merged? Is it worth testing anything at this point or shall we wait until sarietta's pull request is merged with master?

Thanks for all the work on this, it feels like we are very close to having a working python client with the latest SocketIO protocol. :)

**Comment by kctess5** [comment]
Just checked out the code from the pull request and it's working for me with:

socket.io@1.3.3
node v0.10.31

 Way to go @sarietta! Looking forward to the merge.

**Comment by gkawamoto** [comment]
@kctess5 what's your Python version?

I've been having the same warning "socketIO_client:Got unexpected packet during connection handshake: 0". 

— Python 2.7.3
— node v0.10.26
— express@4.11.2
— socket.io@1.3.3

I've checked the pull request but got no luck with my environment.

**Comment by gkawamoto** [comment]
I've found out what was wrong with my environment: I had a package called enum34 installed that was conflicting with the enum used in the socketIO-client. Just uninstalled the enum34 and now we're using the right one.

**Comment by softforge** [comment]
Awesome progress on Sunday, thanks very much! Only 2 issues and 2 pull requests still open... :)

**Comment by invisibleroads** [comment]
We are pleased to announce the official 0.6.1 release of a socket.io client library for Python.

- [0.6.1](https://github.com/invisibleroads/socketIO-client/tree/64fad75d4c452ee10dc4e58be8b1518d8a166a19) implements the socket.io 1.x protocol through the polling transport on [Python 2.6, 2.7 and 3.4](https://travis-ci.org/invisibleroads/socketIO-client).  Not yet supported are websockets, binary events/acks and rooms.
- [0.5.5](https://github.com/invisibleroads/socketIO-client/tree/24ce2dc6c0629d8410092324e4f23aeadaf2d835) implements the socket.io 0.9 protocol.

Thanks to Sean Arietta (@sarietta), Joe Palmer (@softforge) and Guillermo Rauch (@rauchg) for their ideas and encouragement.

**Comment by softforge** [comment]
:+1:

**Comment by softforge** [comment]
I just wanted to say thanks very much! We have now integrated your project into our live system and it's working great!!!

**Comment by invisibleroads** [comment]
I am super happy to hear that!!!!!!!!!!!!!!!!!
Hearing reports of an open source package being used in the wild is the best reward for doing this type of community service.
Thanks for sharing.
